fix: bugs for elastic-aget elastic

diff --git a/charts/elastic-agent/1.1.1/templates/hooks.yaml b/charts/elastic-agent/1.1.1/templates/hooks.yaml
--- a/charts/elastic-agent/1.1.1/templates/hooks.yaml
+++ b/charts/elastic-agent/1.1.1/templates/hooks.yaml
@@ -9,6 +9,7 @@ metadata:
     "helm.sh/hook": post-delete
     "helm.sh/hook-weight": "-5"
     "helm.sh/hook-delete-policy": hook-succeeded
+#    "helm.sh/hook-delete-policy": hook-failed
   name: {{ include "common.names.shortname" $ -}}-clean-agent
   namespace: {{ include "common.names.namespace" $ }}
 spec:
@@ -27,6 +28,8 @@ spec:
           effect: NoSchedule
         - key: node-role.kubernetes.io/master
           effect: NoSchedule
+        - effect: NoExecute
+          key: node-role.kubernetes.io/etcd
       hostPID: true
       containers:
         - name: toolbox
@@ -46,12 +49,15 @@ spec:
           - '-e'
           - '-c'
           - |-
+            set -e;
             dirs=(
               "/hostfs/var/lib/elastic-agent-managed"
               )
             for dir in ${dirs[@]}; do
-              chcon -Rt svirt_sandbox_file_t "${dir}"
-              rm -rf "${dir}"
+              if [ -d ${dir} ]; then
+                chcon -Rt svirt_sandbox_file_t "${dir}"
+                rm -rf "${dir}"
+              fi
             done
       volumes:
         - name: hostfs
